// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:123',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '722',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '123',
    'aws_project_name': 'name',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': '123',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_123',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '123',
}


export default awsmobile;
